Controllers/MemberPagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HukSleva.Controllers
{
    [Authorize("member")]
    public class MemberPagesController : Controller
    {
        
        public IActionResult MainPage()
        {
            return View();
        }
        
        public IActionResult AddBook()
        {
            return View();
        }

        
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HukSleva</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HukSleva</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="SelfInfo" asp-controller="Account">Данные аккаунта</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Catalog" asp-controller="Books">Каталог</a>
                        </li>
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-action="Logout" asp-controller="Account">Ливнуть нахой от сюда</a>
                                </li>
                                <li class="nav-item">
                                    <div class="nav-link " style="color: #ff6a00">
                                        @User.Claims.FirstOrDefault(cl => cl.Type == ClaimsIdentity.DefaultNameClaimType)?.Value
                                    </div>

                                </li>
                                <li class="nav-item">
                                    <div class="nav-link" style="color: #ffd800">
                                        @User.Claims.FirstOrDefault(cl => cl.Type == "dateBirthday")?.Value
                                    </div>

                                </li>
                                <li class="nav-item">
                                    <div class="nav-link" style="color: #b200ff">
                                        @User.Claims.FirstOrDefault(cl => cl.Type == "money")?.Value
                                    </div>

                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-action="ShopingCard" asp-controller="Books">Корзина</a>
                                </li>
                                if (User.IsInRole("admin") || User.IsInRole("moderator"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="MainPage" asp-controller="MemberPages">Для модераторов и админа</a>
                                    </li>
                                }
                                if (User.IsInRole("admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="Index" asp-controller="Home">Для админа</a>
                                    </li>
                                }
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="height:2000px">

        @RenderBody()

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HukSleva - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>