ViewModels/BookController/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UserDataBase;

namespace HukSleva.ViewModels.BookController
{
    public class BookViewModel
    {

        Book _book;
        byte[] img;
        public BookViewModel(Book book, byte[] f)
        {
            _book = book;
            RefreshImg(f);
            Refresh(_book);
        }
        public void Refresh(Book book)
        {
            Comments = new CommentViewModel[book.CommentNum];
            for (int i = 0; i < book.CommentNum; i++)
            {
                Comments[i] = new CommentViewModel(book.Comments[i]);
            }
            
            Author = book.Author;
            Name = book.Name;
            Price = book.Price.ToString();
            Rating = Math.Round(book.Rating, 2).ToString(); 
            Id = book.Id;
            NumRated = book.NumRated.ToString();
        }
        public void RefreshImg(byte[] bs)
        {
            img = bs;
        }
        public string Author { get; set; }
        byte[] _bytes = null;
        byte[] _img = null;
        public byte[] Bytes { get 
            {
                if (_bytes == null)
                {
                    _bytes = null;
                }
                return _bytes;
            } 
        }
        public byte[] Img { get 
            {
                if (_img == null)
                {
                    _img = img;
                }
                return _img;
            } 
        }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Rating { get; set; }
        public int Id { set; get; }
        public CommentViewModel[] Comments { get; private set; }
        string _imgSrc = "";
        public string ImgSrc
        {
            get
            {
                if(_imgSrc == "")
                {
                    var base64 = Convert.ToBase64String(Img ?? new byte[] { });
                    var imgSrc = String.Format("data:image;base64,{0}", base64);
                    _imgSrc = imgSrc;
                }

                return _imgSrc;
            }
        }
        public string NumRated { get; set; }
    }
}

ViewModels/BookController/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UserDataBase;

namespace HukSleva.ViewModels.BookController
{
    public class CommentViewModel
    {
        public CommentViewModel(Comment comment)
        {
            if (comment.Comments.Count > 0 || comment.Comments != null)
            {
                Comments = new CommentViewModel[comment.Comments.Count];
                for (int i = 0; i > comment.Comments.Count; i++)
                {
                    Comments[i] = new CommentViewModel(comment.Comments[i]);
                }
            }
            NumDislikes = comment.Dislikes.ToString();
            NumLikes = comment.NumLikes.ToString();
            Date = comment.Date.ToString("D");
            Text = comment.Text;
        }
        public CommentViewModel[] Comments { private set; get; }
        public string NumDislikes { get; set; }
        public string NumLikes { get; set; }
        public string Date { get; set; }
        public string Text { get; set; }
    }
}

Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HukSleva.ViewModels.ValidationModels.BookValid;
using UserDataBase;
using System.IO;
using HukSleva.ViewModels.BookController;
using HukSleva.Services;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace HukSleva.Controllers
{
    public class BooksController : Controller
    {
        UserDb _db;
        UserFilesDb _filesDb;
        BookViewModelsCollectionService _booksS;

        public BooksController(UserDb userDb, UserFilesDb filesDb, BookViewModelsCollectionService booksS)
        {
            _db = userDb;
            _filesDb = filesDb;
            _booksS = booksS;
            if (_booksS.Count < 1)
            {
                Book[] bs2 = _db.Books.Include(b => b.Comments).ToArray();
                for (int i = 0; i < bs2.Length && i < 10; i++)// 10 ЧИСЛО книг отображаемых на странице - о: оптимизация
                {

                    var img = _filesDb.Files.Find(bs2[i].ImageBytesId).Bytes;
                    var viewModel = new BookViewModel(bs2[i], img);
                    _booksS.Add(viewModel);
                }
            }
        }
        [HttpPost]
        public IActionResult AddBook(AddBookValid book)
        {
            if (book == null)
                return Content("");
            //if (ModelState.IsValid) { }

            if (book.BookBytes == null || book.Img == null)
            {
                ModelState.AddModelError("", "Загрузите книгу и фотографию");
            }
            if (ModelState.IsValid)
            {
                Book book1 = new Book { Author = book.Author, Name = book.Name, Price = book.Price };
                UserFile fImg = new UserFile();
                UserFile fBook = new UserFile();
                fImg.FileType = fileType.img;
                fBook.FileType = fileType.book;
                fImg.Name = "";
                fBook.Name = "";


                using (MemoryStream stream = new MemoryStream())
                {
                    var t = book.Img.FirstOrDefault();
                    if (t == null)
                    {
                        return Content(t + "is null(img)");
                    }
                    t.CopyTo(stream);
                    fImg.Extention = Path.GetExtension(t.Name);
                    t.CopyTo(stream);
                    fImg.Bytes = stream.ToArray();
                }
                using (MemoryStream stream = new MemoryStream())
                {
                    var t = book.BookBytes.FirstOrDefault();
                    if (t == null)
                    {
                        return Content(t + "is null(book)");
                    }
                    t.CopyTo(stream);
                    fBook.Extention = Path.GetExtension(t.Name);
                    t.CopyTo(stream);
                    fBook.Bytes = stream.ToArray();
                }

                var imgEnt = _filesDb.Files.Add(fImg);
                var bookEnt = _filesDb.Files.Add(fBook);
                _filesDb.SaveChanges();


                var imgId = imgEnt.Entity.Id;
                var bookId = bookEnt.Entity.Id;


                book1.ImageBytesId = imgId;
                book1.BookBytesId = bookId;
                var viewModel = new BookViewModel(book1, fImg.Bytes);
                _booksS.Add(viewModel);
                _db.Books.Add(book1);

                _db.SaveChanges();
                return RedirectToAction("Catalog", "Books");

            }
            return View("~/Views/MemberPages/AddBook.cshtml");
        }
        public IActionResult Catalog()
        {
            //var admin = _db.Users.Find(24); admin.Money = 1000; _db.Users.Update(admin); _db.SaveChanges();

            return View(_booksS);
        }
        public IActionResult GetBook(int id)
        {   
            if (id < 1)
            {
                return RedirectToAction("Catalog");
            }
            BookViewModel book = _booksS.FirstOrDefault(b => b.Id == id);
            var b2 = _db.Books.Include(b => b.Comments)?.FirstOrDefault(b => b.Id == id);
            book?.Refresh(b2);
            ViewBag.UserId = int.Parse(User.FindFirst("id").Value);
            return View(book);
        }
        public IActionResult MakeReading(int idBook, int idUser)
        {
            var book = _db.Books.Find(idBook);
            var user = _db.Users.Include(u => u.History).Include(u => u.Reading).FirstOrDefault(u => u.Id == idUser);
            user.History = user.History ?? new History { User = user, UserId = user.Id };
            if (book != null && user != null && user.History.Bought.FirstOrDefault(b => b.Id == idBook) != null)
            {
                var identity = User.Identity as ClaimsIdentity;
                identity.RemoveClaim(identity.FindFirst("readingBookId"));
                identity.AddClaim(new Claim("readingBookId", $"{idBook}"));
                // установка аутентификационных куки
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
                user.Reading = book;
                _db.SaveChanges();
            }
            return RedirectToAction("GetBook", new { id = idBook });
        }
        public IActionResult MakeRead(int idBook, int idUser)
        {
            var book = _db.Books.Find(idBook);
            var user = _db.Users.Include(u => u.History).Include(u => u.Reading).FirstOrDefault(u => u.Id == idUser);
            user.History = user.History ?? new History { User = user, UserId = user.Id };
            if (book != null && user != null && user.History.Bought.FirstOrDefault(b => b.Id == idBook) != null)
            {
                var identity = User.Identity as ClaimsIdentity;
                var readingIdBook = user.Reading?.Id;
                if (readingIdBook == idBook)
                {
                    identity.RemoveClaim(identity.FindFirst("readingBookId"));
                    identity.AddClaim(new Claim("readingBookId", $""));
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
                    user.Reading = null;
                }

                user.History.Read = user.History.Read ?? new List<Book>();
                if (user.History.Read.FirstOrDefault(b => b.Id == book.Id) == null)
                {
                    user.History.Read.Add(book);
                }
                _db.Users.Update(user);
                _db.SaveChanges();
            }
            return RedirectToAction("GetBook", new { id = idBook });
        }
        public IActionResult AddRating(int idBook, int score, int idUser)
        {
            var b = _db.Books.Find(idBook);
            
            var user = _db.Users.Include(u => u.History).Include(u => u.History.Reated).FirstOrDefault(u => u.Id == idUser);
            if (user.History == null)
            {
                user.History = new History();
            }
            if (user.History.Reated == null)
            {
                user.History.Reated = new List<Book>();
            }
            var isNotRated = user.History.Reated.FirstOrDefault(b => b.Id == idBook) is null;
            if (b != null && user != null && isNotRated)
            {
                var rating = ((b.Rating * b.NumRated) + score) / (++b.NumRated);
                b.Rating = rating;


                

                user.History.Reated.Add(b);
                _db.Users.Update(user);
                _db.Books.Update(b);
                _db.SaveChanges();
            }
            return RedirectToAction("GetBook", new { id = idBook });
        }
        public IActionResult BuyBook(int idBook, int idUser)
        {
            var book = _db.Books.Find(idBook);
            var user = _db.Users.Include(u => u.History).Include(u => u.Reading).FirstOrDefault(u => u.Id == idUser);
            if (book != null && user != null)
            {
                var readingIdBook = user.Reading?.Id;
                user.History = user.History ?? new History { User = user, UserId = user.Id };
                user.History.Bought = user.History.Bought ?? new List<Book>();
                if (book.Price <= user.Money && user.History.Bought.FirstOrDefault(b => b.Id == book.Id) == null)
                {
                    user.Money -= book.Price;
                    var identity = User.Identity as ClaimsIdentity;
                    identity.RemoveClaim(identity.FindFirst("money"));
                    identity.AddClaim(new Claim("money", $"${user.Money}"));
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
                    user.History.Bought.Add(book);
                }
                _db.Users.Update(user);
                _db.SaveChanges();
            }
            return RedirectToAction("GetBook", new { id = idBook });
        }
        public IActionResult ShopingCard()
        {
            int userId = -1;
            int.TryParse(User.Claims.First(c => c.Type == "id").Value, out userId);
            
            var user = _db.Users.Include(u => u.ShoppingCard).Include(u => u.ShoppingCard.Books).FirstOrDefault(u => u.Id == userId); 
            if (user != null)
            {
                if (user.ShoppingCard == null)
                {
                    user.ShoppingCard = new ShoppingCard();
                }

ViewsComponents/BookViewComponent.cs
using HukSleva.ViewModels.BookController;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HukSleva.ViewsComponents
{
    public class BookViewComponent : ViewComponent
    {
        private bool _isFullView;
        public IViewComponentResult Invoke(BookViewModel book, bool isFullView = false)
        {
            _isFullView = isFullView;

            ViewBag.isFullView = _isFullView;

            return View(book);
        }
    }
}

Views/Books/Catalog.cshtml
@using HukSleva.ViewModels.BookController;
@using HukSleva.Services;

@model BookViewModelsCollectionService;



@{
    var next = Model?.First;
    while (next != null)
    {
        @await Component.InvokeAsync("Book", new { book = next?.Value })
        next = next?.Next;
    }
}


Views/Books/Comment.cshtml
@using HukSleva.ViewModels.BookController;

@model CommentViewModel[]

@if (User.Identity.IsAuthenticated)
{
    <div>
        <form method="post" asp-action="ValidComment" asp-controller="ValidComment" asp-route-idBook="@ViewData["bId"]" asp-route-idUser ="@ViewBag.UserId">
            <div>
                <div class="validation" asp-validation-summary="All"></div>
                <div>
                    <label>Комментарий</label><br />
                    <textarea name="commentText" type="text"></textarea>
                </div>
                <button type="submit"></button>
            </div>
        </form>
    </div>
}


<article>
    @{
        for (int i = 0; i < (Model?.Length ?? 0); i++)
        {
            var m = Model[i];
        <div style="border: 3px 3px 3px 3px">
            @m.Date
            <br />
            @m.Text;
            <br />
            
        </div>
        }
    }
</article>

Views/Books/ForAdulthooder.cshtml

    for aduthhoolder


Views/Books/GetBook.cshtml
@using HukSleva.ViewModels.BookController
@model BookViewModel
<div class="d-flex flex-column" style="width:100%; height: 100%">
    <div class="d-flex flex-column h-25">
        <a asp-action="MakeReading" asp-controller="Books" asp-route-idUser="@ViewBag.UserId" asp-route-idBook="@Model.Id">Сделать текущей</a>
        <a asp-action="MakeRead" asp-controller="Books" asp-route-idUser="@ViewBag.UserId" asp-route-idBook="@Model.Id">добавить в список прочитанных</a>
        <a asp-action="BuyBook" asp-controller="Books" asp-route-idUser="@ViewBag.UserId" asp-route-idBook="@Model.Id">Купить</a>
        <a asp-action="AddBookInShopingCard" asp-controller="Books" asp-route-idUser="@ViewBag.UserId" asp-route-idBook="@Model.Id">Добавить в корзину</a>
        <div class="d-flex">
            <a asp-action="AddRating" asp-controller="Books" asp-route-idBook="@Model.Id" asp-route-score="1" asp-route-idUser="@ViewBag.UserId">1</a>
            <a asp-action="AddRating" asp-controller="Books" asp-route-idBook="@Model.Id" asp-route-score="2" asp-route-idUser="@ViewBag.UserId">2</a>
            <a asp-action="AddRating" asp-controller="Books" asp-route-idBook="@Model.Id" asp-route-score="3" asp-route-idUser="@ViewBag.UserId">3</a>
            <a asp-action="AddRating" asp-controller="Books" asp-route-idBook="@Model.Id" asp-route-score="4" asp-route-idUser="@ViewBag.UserId">4</a>
            <a asp-action="AddRating" asp-controller="Books" asp-route-idBook="@Model.Id" asp-route-score="5" asp-route-idUser="@ViewBag.UserId">5</a>
        </div>
        <div>
            <img src="@Model.ImgSrc" />
        </div>

        <div class="d-flex flex-column">
            <div>Название @Model.Name</div>
            <div>Автор @Model.Author</div>
            <div>Цена @Model.Price</div>
            <div>Рейтинг @Model.Rating</div>
            <div>Проголосвало @Model.NumRated</div>
        </div>

    </div>
    <div class="d-flex flex-column h-25">

    </div>
    <div class="d-flex h-50 flex-column">
        @{
            ViewDataDictionary vData = new ViewDataDictionary(ViewData);
            vData.Add("bId", $"{Model.Id}");
        }
        @await Html.PartialAsync("Comment", Model.Comments, vData)
    </div>
</div>